<?php
/*
 * Language translation for shipping extension - carrier Old Dominion
 *
 * NOTICE OF LICENSE
 * This software may be used only for one installation of Bizuno when
 * purchased through the PhreeSoft.com website store. This software may
 * not be re-sold or re-distrubuted without written consent of Phreesoft.
 * Please contact us for further information or clarification of you have
 * any questions.
 *
 * DISCLAIMER
 * Do not edit or add to this file if you wish to automatically upgrade to
 * a newer version in the future. If you wish to customize this module, you
 * do so at your own risk, PhreeSoft will not support this extension if it
 * has been modified from its original content.
 *
 * @name       Bizuno ERP
 * @author     Dave Premo, PhreeSoft <support@phreesoft.com>
 * @copyright  2008-2020, PhreeSoft, Inc.
 * @license    PhreeSoft Proprietary
 * @version    4.x Last Update: 2020-09-05
 * @filesource /lib/locale/fr_CA/ext/extShipping/carriers/odlf/language.php
 */

$lang = [
    'title' => 'Old Dominion USA',
    'acronym' => 'ODFL',
    'description' => 'This method provides discounted quotes based on your ODFL contracted account. You will need an account at <a href="http://www.odfl.com" target="_blank">www.odfl.com</a> to use this carrier. Labels must be generated by hand or through their website.',
    'username' => 'Enter the ODFL user name used to log into your account at www.odfl.com',
    'password' => 'Enter the ODFL password used to log into your account at www.odfl.com',
    'account'  => 'Enter your ODFL account number provided to you by ODFL.',
    'min_weight' => 'The minimum weight of shipment to request a rate quote for this carrier.',
    'GDF' => 'LTL Speed Service Guaranteed',
    'ECF' => 'LTL Standard Service',
    'ltl_std' => 'Approx. Transit: %s Day(s)',
    'ltl_guar'=> 'Guaranteed Transit: %s Day(s)',
   ];
