<?php
/*
 * Langue de traduction pour l'extension expédition - transporteur XPO Logistics
 *
 * NOTICE OF LICENSE
 * This software may be used only for one installation of Bizuno when
 * purchased through the PhreeSoft.com website store. This software may
 * not be re-sold or re-distrubuted without written consent of Phreesoft.
 * Please contact us for further information or clarification of you have
 * any questions.
 *
 * DISCLAIMER
 * Do not edit or add to this file if you wish to automatically upgrade to
 * a newer version in the future. If you wish to customize this module, you
 * do so at your own risk, PhreeSoft will not support this extension if it
 * has been modified from its original content.
 *
 * @name       Bizuno ERP
 * @author     Dave Premo, PhreeSoft <support@phreesoft.com>
 * @copyright  2008-2020, PhreeSoft, Inc.
 * @license    PhreeSoft Proprietary
 * @version    4.x Last Update: 2020-09-05
 * @filesource /lib/locale/fr_CA/ext/extShipping/carriers/xpo/language.php
 */

$lang = [
    'title' => 'XPO Logistics (USA)',
    'acronym' => 'XPO',
    'description' => 'This method provides discounted quotes based on your XPO contracted account. The credentials (user name, password, and AcctID) must be applied for through your local XPO Representative. Labels must be generated by hand or through their website, <a href="http://www.xpo.com" target="_blank">www.xpo.com</a>.',
    'username' => 'Enter the XPO user name used to register with XPO.',
    'password' => 'Enter the XPO password used to register XPO.',
    'acct_id' => 'Enter the XPO Acct Number provided to you by XPO.',
    'min_weight' => 'The minimum weight of shipment to request a rate quote for this carrier.',
    'ECF' => 'LTL Ground Freight'];
